import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import markdown
import yaml

# Load environment variables
load_dotenv()

class EmailClient:
    def __init__(self):
        self.smtp_server = os.getenv("SMTP_SERVER")
        self.smtp_port = int(os.getenv("SMTP_PORT", 587))
        self.username = os.getenv("SMTP_USER")
        self.password = os.getenv("SMTP_PASS")
        self.sender_email = os.getenv("SMTP_FROM", self.username)
        
        # Load recipients from config.yaml
        self.recipients = self._load_recipients()

    def _load_recipients(self):
        """Load recipients from config.yaml or fallback to env var."""
        try:
            project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            config_path = os.path.join(project_dir, "config.yaml")
            
            if os.path.exists(config_path):
                with open(config_path, 'r') as f:
                    config = yaml.safe_load(f)
                    recipients = config.get('notification', {}).get('email', {}).get('recipients', [])
                    if recipients:
                        return [r.strip() for r in recipients if r and r.strip()]
        except Exception as e:
            print(f"Error loading recipients from config.yaml: {e}")
            
        # Fallback to env var
        recipients_str = os.getenv("SMTP_TO", "")
        return [r.strip() for r in recipients_str.split(",") if r.strip()]

    def send_email(self, subject, markdown_content):
        """Send an email with the given subject and markdown content (converted to HTML)."""
        if not self.smtp_server or not self.username or not self.password or not self.recipients:
            return "Email configuration missing (SMTP_SERVER, SMTP_USER, SMTP_PASS, SMTP_TO)"

        try:
            # Convert Markdown to HTML
            html_content = markdown.markdown(markdown_content, extensions=['extra', 'codehilite'])
            
            # Wrap in a simple HTML template for better styling
            full_html = f"""
            <html>
            <head>
                <style>
                    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
                    h1, h2, h3 {{ color: #2c3e50; border-bottom: 1px solid #eee; padding-bottom: 10px; }}
                    a {{ color: #0366d6; text-decoration: none; }}
                    a:hover {{ text-decoration: underline; }}
                    code {{ background-color: #f6f8fa; padding: 2px 4px; border-radius: 3px; font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, monospace; font-size: 85%; }}
                    pre {{ background-color: #f6f8fa; padding: 16px; border-radius: 6px; overflow: auto; }}
                    blockquote {{ border-left: 4px solid #dfe2e5; color: #6a737d; padding-left: 16px; margin-left: 0; }}
                    ul, ol {{ padding-left: 20px; }}
                    li {{ margin-bottom: 5px; }}
                    .footer {{ margin-top: 40px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }}
                </style>
            </head>
            <body>
                {html_content}
                <div class="footer">
                    Generated by AI News Aggregator | <a href="https://github.com/zhanfang/ai-news">View on GitHub</a>
                </div>
            </body>
            </html>
            """

            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = self.sender_email
            msg["To"] = ", ".join(self.recipients)

            # Attach both plain text (as fallback) and HTML
            part1 = MIMEText(markdown_content, "plain")
            part2 = MIMEText(full_html, "html")
            msg.attach(part1)
            msg.attach(part2)

            # Connect and send
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.username, self.password)
                server.sendmail(self.sender_email, self.recipients, msg.as_string())

            return f"Email sent successfully to {len(self.recipients)} recipients"

        except Exception as e:
            return f"Failed to send email: {str(e)}"
